# Model Configuration File
# This file contains configuration parameters for machine learning models

# Neural Network Configuration
neural_network:
  input_size: 784  # For MNIST-like data (28x28 images)
  hidden_sizes: [128, 64]
  num_classes: 10
  dropout_rate: 0.2
  activation: "relu"

# CNN Configuration
cnn:
  input_channels: 3  # RGB images
  num_classes: 10
  conv_layers:
    - filters: 32
      kernel_size: 3
      padding: 1
    - filters: 64
      kernel_size: 3
      padding: 1
    - filters: 128
      kernel_size: 3
      padding: 1
  pool_size: 2
  fc_hidden_size: 512
  dropout_rate: 0.5

# Training Configuration
training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 10
  optimizer: "adam"
  loss_function: "cross_entropy"
  weight_decay: 0.0001
  
# Data Configuration
data:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  image_size: [224, 224]  # Height, Width
  normalize_mean: [0.485, 0.456, 0.406]  # ImageNet mean
  normalize_std: [0.229, 0.224, 0.225]   # ImageNet std
  
# Computer Vision Configuration
computer_vision:
  blur_kernel_size: 5
  edge_detection:
    low_threshold: 50
    high_threshold: 150
  contour_detection:
    mode: "external"
    method: "simple"
    
# Paths
paths:
  data_dir: "data/"
  model_dir: "data/models/"
  log_dir: "logs/"
  checkpoint_dir: "data/models/checkpoints/"